
    $(document).ready(function(){
        $('#mycarousel').carousel({interval: 2000});
        /*$('#carousel-pause').click(function(){
            $('#mycarousel').carousel('pause');
        });
        $('#carousel-play').click(function(){
            $('#mycarousel').carousel('play');
        });*/
        $('#carouselButton').click(function(){
            if($('#carouselButton').children('span').hasClass('fa-pause')){
                $('#mycarousel').carousel('pause');
                $('#carouselButton').children('span').removeClass('fa-pause');
                $('#carouselButton').children('span').addClass('fa-play');
            }
            else{
                $('#mycarousel').carousel('cycle');
                $('#carouselButton').children('span').removeClass('fa-play');
                $('#carouselButton').children('span').addClass('fa-pause');                
            }
        });
        $('#loginBut').click(function(){
            $('#loginModal').modal('toggle');
        });
        $('#reserveBut').click(function(){
            $('#reserveModal').modal('toggle');
        });
        $("#loginModalHeader").click(function(){
            $('#loginModal').modal('hide');
        });
        $("#loginModalButton").click(function(){
            $('#loginModal').modal('hide');
        });
        $("#reserveModalHeader").click(function(){
            $('#reserveModal').modal('hide');
        });
        $("#reserveModalButton").click(function(){
            $('#reserveModal').modal('hide');
        });
    });
